# Chapter 1. Vectors, Matrices, and Arrays in NumPy

### 1.0 Introduction

**NumPy (Numerical Python)** is a library for the Python programming language, used for working with large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. 

### 1.1 Create a Vector

A vector is simply a one-dimensional (1-D) array which can represent anything from a list of numbers to a set of values like coordinates or measurements.

In [1]:
import numpy as np

# Row Vector
vector_row = np.array([1, 2, 3, 4], dtype=int)
print(vector_row)

# Column Vector
vector_col = np.array([[1],
                       [2],
                       [3],
                       [4]], dtype=int)
print(vector_col)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


### 1.2 Create a Matrix

A matrix is a way to organize numbers in a rectangular grid made up of rows (m) and columns (n). In Python, it is a two-dimensional (2-D) array.

In [2]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]], dtype=int)
print(matrix)

[[1 2 3]
 [4 5 6]]


### 1.3 Create a Sparse Matrix

Matrices that contain mostly zero values are called **sparse**, distinct from matrices where most of the values are non-zero, called **dense**. So, Sparse matrices store
only nonzero elements and their indices, leading to significant computational savings. 

Types of Sparse Matrix:
- **Compressed Sparse Row**: The sparse matrix is represented using three 1D arrays for the non-zero values, the extents of the rows, and the column indexes.
- **Compressed Sparse Column**: The same as the Compressed Sparse Row method except the column indices are compressed and read first before the row indices.
- **Dictionary of Keys**: A dictionary is used where a row and column index is mapped to a value.
- **List of Lists**: Each row of the matrix is stored as a list, with each sublist containing the column index and the value.
- **Coordinate List**: A list of tuples is stored with each tuple containing the row index, column index, and the value.


In [3]:
from scipy import sparse

matrix = np.array([[0, 0, 0, 4],
                   [1, 0, 0, 9]], dtype=int)

sparse_matrix = sparse.csr_matrix(matrix)
print(sparse_matrix)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (2, 4)>
  Coords	Values
  (0, 3)	4
  (1, 0)	1
  (1, 3)	9


### 1.4 Preallocate NumPy Arrays

NumPy has functions for generating vectors and matrices of any size using 0s,
1s, or values of your choice.

In [4]:
zeros_vector = np.zeros(5, dtype=int)
print(zeros_vector)

ones_vector = np.ones(5, dtype=int)
print(ones_vector)

matrix = np.full((3, 3), fill_value=23, dtype=int)
print(matrix)

[0 0 0 0 0]
[1 1 1 1 1]
[[23 23 23]
 [23 23 23]
 [23 23 23]]


### 1.5 Select Elements

NumPy offers a wide variety of methods for selecting (i.e., indexing and slicing) elements or groups of elements in arrays.

In [5]:
vector = np.array([1, 2, 3, 4, 5, 6], dtype=int)
print("All elements of a vector: ", vector[:])
print("Third element of vector: ", vector[2])
print("Everything up to and including the third element: ", vector[:3])
print("Everything after the third element: ", vector[3:])
print("Last element: ", vector[-1])
print("Reverse the vector: ", vector[::-1])

matrix = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print("Third element on second row: ", matrix[1, 2])
print("First two rows and all columns of a matrix: ", matrix[:2, :])
print("All rows and the second column: ", matrix[:, 1:2])

All elements of a vector:  [1 2 3 4 5 6]
Third element of vector:  3
Everything up to and including the third element:  [1 2 3]
Everything after the third element:  [4 5 6]
Last element:  6
Reverse the vector:  [6 5 4 3 2 1]
Third element on second row:  6
First two rows and all columns of a matrix:  [[1 2 3]
 [4 5 6]]
All rows and the second column:  [[2]
 [5]]


### 1.6 Describe a Matrix

Describe the shape, size, and number of dimensions of a matrix.

In [6]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Shape of the matrix: ", matrix.shape)
print("Size of the matrix: ", matrix.size)
print("Dimensions of the matrix: ", matrix.ndim)

Shape of the matrix:  (3, 4)
Size of the matrix:  12
Dimensions of the matrix:  2


### 1.7 Apply Functions over Each Element

The NumPy `vectorize` method converts a function into a function that can
apply to all elements in an array or slice of an array.

In [7]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
add_100 = lambda i: (i + 100)
vectorized_function = np.vectorize(add_100)
print(vectorized_function(matrix))

[[101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]


NumPy arrays allow us to perform operations between arrays even if their dimensions are not the same (a process called **broadcasting**).

In [8]:
print(matrix + 100)

[[101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]


### 1.8 Find Descriptive Statistics

Find max, min, average, variance, and standard deviation of a matrix

In [9]:
print("Maximum element in matrix: ", np.max(matrix))
print("Maximum element in each column of matrix: ", np.max(matrix, axis=0))
print("Minimum element in matrix: ", np.min(matrix))
print("Minimum element in each row of matrix: ", np.min(matrix, axis=1))
print("Average of the matrix: ", np.mean(matrix))
print("Variance of the matrix: ", np.var(matrix))
print("Standard deviation of the matrix: ", np.std(matrix))

Maximum element in matrix:  12
Maximum element in each column of matrix:  [ 9 10 11 12]
Minimum element in matrix:  1
Minimum element in each row of matrix:  [1 5 9]
Average of the matrix:  6.5
Variance of the matrix:  11.916666666666666
Standard deviation of the matrix:  3.452052529534663


### 1.9 Reshape Arrays

`reshape(row, column)` allows us to restructure an array so that we maintain the same data but organize it as a different number of rows and columns. And, Size of the matrix will remain same.

In [10]:
print(matrix.reshape(2, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


One useful argument in `reshape` is -1, which effectively means “as many as
needed,” so `reshape(1, -1)` means one row and as many columns as
needed.

In [11]:
print(matrix.reshape(1, -1))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


If only one integer is provided in `reshape`, it will return a 1D array of that length.

In [12]:
print(matrix.reshape(12))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### 1.10 Transpose a Vector or Matrix

Transposing means swapping the column and row indices of each element. 

In [13]:
print(matrix.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 1.11 Flatten a Matrix

`flatten` is a method to transform a matrix into a one-dimensional
array. flatten is a simple method to transform a matrix into a one-dimensional
array.

In [14]:
print(matrix.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Another common way to flatten arrays is the `ravel` method. Unlike `flatten`,
which returns a copy of the original array, `ravel` operates on the original object
itself and is therefore slightly faster.

In [15]:
print(matrix.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### 1.12 Find the Rank of Matrix

The **rank** of a matrix is the dimensions of the vector space spanned by its columns or rows.

In [16]:
print(np.linalg.matrix_rank(matrix))

2


### 1.13 Get the Diagonal of Matrix

Use `diagonal` to get diagonal elements of a matrix.

In [17]:
print(matrix.diagonal())

[ 1  6 11]


Use `offset` parameter to get another diagonals.

In [18]:
print(matrix.diagonal(offset=1))

[ 2  7 12]


### 1.14 Trace of Matrix

The trace of a matrix is the sum of the diagonal elements.

In [19]:
print(matrix.trace())

18


### 1.15 Calculate Dot Products

The dot product of two vectors, a and b, is defined as:
$$\sum a_ib_i$$
where $a_i$ is the ith element of vector a, and $b_i$ is the ith element of vector b. 

In [20]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

print(np.dot(vector_a, vector_b))
print(vector_a @ vector_b)

32
32


### 1.16 Add and Subtract Matrices

In [21]:
matrix_a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(matrix_a + matrix_b)
print(np.add(matrix_a, matrix_b))

print(matrix_a - matrix_b)
print(np.subtract(matrix_a, matrix_b))

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### 1.17 Multiply Matrices

In [22]:
# Dot Product
print(np.dot(matrix_a.T, matrix_b))

# Element-wise multiplication
print(matrix_a * matrix_b)

[[107 122 137 152]
 [122 140 158 176]
 [137 158 179 200]
 [152 176 200 224]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


### 1.18 Invert a Matrix

The inverse of a square matrix, $A$, is a second matrix, $A^{-1}$, such that:
$$AA^{-1}=I$$
where $I$ is the **Identity Matrix**. In NumPy we can use `linalg.inv` to calculate
$A^{–1}$ if it exists.

In [23]:
matrix = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(matrix))

[[-2.   1. ]
 [ 1.5 -0.5]]


### 1.19 Generate Random Values

In [24]:
from numpy import random

random.seed(0)

print("Three random floats between 0.0 and 1.0: ", random.random(3))
print("Three random integers between 0 and 10: ", random.randint(low=0, high=11, size=3))
print("Three random numbers from normal dist. with mean 0.0 and std of 1.0: ", random.normal(0.0, 1.0, 3))
print("Three random numbers from logistic dist. with mean 0.0 and scale of 1.0: ", random.logistic(0.0, 1.0, 3))
print("Three random numbers greater than or equal to 1.0 and less than 2.0: ", random.uniform(0.0, 1.0, 3))

Three random floats between 0.0 and 1.0:  [0.5488135  0.71518937 0.60276338]
Three random integers between 0 and 10:  [3 7 9]
Three random numbers from normal dist. with mean 0.0 and std of 1.0:  [-1.42232584  1.52006949 -0.29139398]
Three random numbers from logistic dist. with mean 0.0 and scale of 1.0:  [-0.98118713 -0.08939902  1.46416405]
Three random numbers greater than or equal to 1.0 and less than 2.0:  [0.47997717 0.3927848  0.83607876]
